print(' ================ TABELA VERDADE 1 ================')
print('  Not False =', not True)
print('  Not True =',  not False)
print(' ================ TABELA VERDADE 2 ================')
print('  True and True',   True and True)
print('  True and False',  True and False)
print('  False and True',  False and True)
print('  False and False', False and False)
print(' ================ TABELA VERDADE 3 ================')
print('  True or True',   True or True)
print('  True or False',  True or False)
print('  False or True',  False or True)
print('  False or False', False or False)
print(' ==================================================')